### ISSUE TITLE
2016高校列表更新

### ISSUE THREAD

**Issue by haoranyu** [WenryXu/ChinaUniversity#1]
### 有如下变化
- 相比于当前 Repo 中的列表

#### 应并入
云南热带作物职业学院 -> 云南农业大学（热带作物学院）
上海健康职业技术学院 -> 上海健康医学院
北京现代职业技术学院 -> 北京城市学院（职业技术学院）
上海立信会计学院 -> 上海立信会计金融学院
上海金融学院 -> 上海立信会计金融学院

#### 应添加
北京网络职业学院
唐山幼儿师范高等专科学校
长春师范高等专科学校
吉林职业技术学院
盐城幼儿师范高等专科学校
苏州幼儿师范高等专科学校
江苏航空职业技术学院
江苏安全技术职业学院
浙江安防职业技术学院
赣南卫生健康职业学院
烟台黄金职业学院
湖北铁道运输职业学院
武汉海事职业学院
武当职业学院
荆门职业学院
武汉铁路桥梁职业学院
广东茂名健康职业学院
广东酒店管理职业技术学院
广东茂名幼儿师范专科学校
广州卫生职业技术学院
湛江幼儿师范专科学校
玉柴职业技术学院
广西蓝天航空职业学院
海南体育职业技术学院
重庆资源与环境保护职业学院
重庆护理职业学院
贵州工程职业学院
贵州工贸职业学院
贵州水利水电职业技术学院
贵州电子商务职业技术学院
贵州应用技术职业学院
贵州电子科技职业学院
贵州航空职业技术学院
昆明铁道职业技术学院
昭通卫生职业学院
大理护理职业学院
云南水利水电职业学院
陕西机电职业技术学院
甘肃能源化工职业学院
兰州现代职业学院
平凉职业技术学院
甘肃财贸职业学院

#### 应更名
河北外国语职业学院 -> 河北对外经贸职业学院
上海公安高等专科学校 -> 上海公安学院
上海城市管理职业技术学院 -> 上海城建职业学院
河南化工职业学院 -> 河南应用技术职业学院
湘潭职业技术学院 -> 湘潭医卫职业技术学院
湖南科技工业职业技术学院 -> 湖南国防工业职业技术学院
宁夏防沙治沙职业技术学院  -> 宁夏葡萄酒与防沙治沙职业技术学院
琼州学院 -> 海南热带海洋学院
上海建峰职业技术学院 -> 上海城建职业学院
天津中德职业技术学院 -> 天津中德应用技术大学

*请参考：http://www.moe.gov.cn/srcsite/A03/moe_634/201606/t20160603_248263.html*

**Comment by WenryXu** [comment]
https://github.com/WenryXu/ChinaUniversity/commit/aeec36cced71f07f81efc1ab627221b46bc79b9f

**Comment by WenryXu** [comment]
已同步至 Jisuanke2
